language: node_js
node_js:
  - "stable"
script:
  - npm rebuild
  - npm install
  - npm run build
after_success:
  - npm run add-domain  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  
  keep-history: true
  local-dir: ./public/
  target_branch: master
  on:
    branch: develop